Add pre/post cleanup for windows GPU test jobs (#1361)
## Motivation

Increase robustness by cleaning up orphaned processes that cause random
and immediate job test failures as seen in
https://github.com/ROCm/TheRock/issues/792 and more recently,
https://github.com/ROCm/TheRock/issues/1346 which ultimately was a
result of https://github.com/ROCm/TheRock/issues/1347.

## Technical Details

On some non-ephemeral Windows GPU runners, test jobs will timeout, be
considered complete by Github Actions, but will leave orphaned processes
running that do not get cleaned up by Github Action's default `Complete
Job` step. This would cause any future test jobs to fail their first
step of `Checkout Repository` which tries to delete the repository
folder from where the running orphaned executable and its libraries
exists.

Windows does not allow this and often will result in errors like this:
`
Error: File was unable to be removed Error: EPERM: operation not
permitted, unlink
'C:\runner\_work\TheRock\TheRock\build\bin\amd_comgr0701.dll'
`
or
`File was unable to be removed Error: EPERM: operation not permitted,
unlink 'B:\actions-runner\_work\TheRock\TheRock\build\bin\rocblas.dll'`

In this case, `rocblas-test.exe` would be an orphaned process still
running.

Detailed analysis can be found here
https://github.com/ROCm/TheRock/issues/792#issuecomment-2957535765

More recently, @marbre discovered earlier error messages that implicates
the orphaned processes within the `Checkout Repository` step itself in
this
https://github.com/ROCm/TheRock/issues/1346#issuecomment-3236014524,
copied here:
```haskell
Cleaning the repository
  "C:\Program Files\Git\cmd\git.exe" clean -ffdx
  warning: failed to remove build/bin/amdhip64_7.dll: Invalid argument
  warning: failed to remove build/bin/amd_comgr0701.dll: Invalid argument
  warning: failed to remove build/bin/rocsparse-test.exe: Invalid argument
  warning: failed to remove build/bin/rocsparse.dll: Invalid argument
[..]
Warning: Unable to clean or reset the repository. The repository will be recreated instead.
Deleting the contents of 'B:\actions-runner\_work\TheRock\TheRock'
Error: File was unable to be removed Error: EPERM: operation not permitted, unlink 'B:\actions-runner\_work\TheRock\TheRock\build\bin\rocsparse-test.exe'
```

This can happen with any job that uses non-ephemeral runners such as in
the following jobs:
- `Configure test matrix` 
- `Test Sanity Check`
- `Test roc...` or `Test hip...`

The initial implementation is with a process clean up powershell script
that is called by newly inserted pre-job and post-job steps in each of
the above jobs. There were discussions to move these steps to be a part
of runner machine setup in the future to allow for more portability.

## Test Plan

- Local testing of script with mocked up directories
- Add windows gpu test and watch CI 

## Test Result

- Local testing passed with mocked processes:
```haskell
PS A:\runner\_work\TheRock\TheRock\build\bin> . 'A:\dev\TheRock\build_tools\github_actions\cleanup_processes.ps1'    
[*] GITHUB_WORKSPACE env var defined: A:\actions-runner\_work\TheRock\TheRock
[*] Checking for running build executables filtered by .exe regex: A:\\actions-runner\\_work\\TheRock\\TheRock\\build\\.*[.]exe
[*] Found 1 running build executable(s):
    > A:\actions-runner\_work\TheRock\TheRock\build\bin\hiprand-test.exe
[*] Attempting to stop executable(s) forcefully...
    > hiprand-test.exe
[+] All 1 executable(s) were stopped.
```

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.

---------

Co-authored-by: Marius Brehler <marius.brehler@amd.com>