Fix `subprocess.CalledProcessError` in HIPIFY Commit Workflow (#1461)
## Motivation
Progress on #1149 
Eliminate the `git commit` errors like below:
```
subprocess.CalledProcessError: Command '['git', 'commit', '-m', 'DO NOT SUBMIT: HIPIFY', '--no-gpg-sign']' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```
## Technical Details

- Added check for staged changes using `git diff --cached --quiet` to
skip commits when no changes are staged.
- Handled exit code 1 in `git commit` with a descriptive message instead
of raising an exception.
- Refactored commit logic into `commit_hipify_module` for clarity and
maintainability, addressing review feedback on control flow.
- Ensured consistent tagging with `tag_hipify_diffbase` even when
commits are skipped.

## Test Plan
<!-- Explain any relevant testing done to verify this PR. -->
Run multiple `build_windows_pytorch_wheels` workflow instanced and
detect missing folder warnings like:

`2025-09-11T17:16:57.6642901Z warning: could not open directory
'onnx/backend/test/data/node/test_dequantizelinear_e4m3fn_float16/': No
such file or directory`

And see how the solution is provided for the situation:
```
2025-09-11T17:17:37.8868758Z ++ Exec [B:\src\torch\third_party\onnx]$ git add -A
2025-09-11T17:17:37.8869024Z No staged changes in B:\src\torch\third_party\onnx after git add: Skipping commit
2025-09-11T17:17:37.8869346Z ++ Exec [B:\src\torch\third_party\onnx]$ git tag -f THEROCK_HIPIFY_DIFFBASE --no-sign
```

The test shows that we removed the errors like:
```
subprocess.CalledProcessError: Command '['git', 'commit', '-m', 'DO NOT SUBMIT: HIPIFY', '--no-gpg-sign']' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```
The test link:
https://github.com/ROCm/TheRock/actions/runs/17651604534/job/50163840102

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.