Apply gentest.py patch to fix rocblas testing on CI. (#1383)
## Motivation

> [!NOTE]
> Also sent upstream as https://github.com/ROCm/rocm-libraries/pull/1443

Progress on https://github.com/ROCm/rocm-libraries/issues/535. Seeing if
this fixes our rocblas tests that have been failing on WIndows like
https://github.com/ROCm/TheRock/actions/runs/17438210230/job/49520134395

```
INFO:root:++ Exec [C:\runner\_work\TheRock\TheRock]$ ./build/bin/rocblas-test --yaml ./build/bin/rocblas_smoke.yaml
rocBLAS info: client (OPENMP) reduced omp_set_num_threads to 10
rocBLAS info: Using reference library 'OpenBLAS::OpenBLAS'
rocBLAS warning: Reference library may not support 64-bit input arguments. If running a test suite, please use --gtest_filter=-*stress* to avoid 64-bit test failures.
rocBLAS version: 5.1.0.3eb64eb743
rocBLAS-commit-hash: ee48e295edc2622868613c021a1c58168f651f81
Tensile-commit-hash: 
hipBLASLt version: 1.1.0 commit-hash: 3eb64eb743
Query device success: there are 1 devices
-------------------------------------------------------------------------------
Device ID 0 : AMD Radeon(TM) 8040S Graphics gfx1151
with 9.0 GB memory, max. SCLK 2700 MHz, max. MCLK 800 MHz, memoryBusWidth 32 Bytes, compute capability 11.5
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 32
-------------------------------------------------------------------------------
info: parsing of test data may take a couple minutes before any test output appears...

C:\runner\_work\TheRock\TheRock\build\bin\/rocblas_gentest.py --template C:\runner\_work\TheRock\TheRock\build\bin\/rocblas_template.yaml -o C:\WINDOWS\SystemTemp\rocblas-fu7qHn ./build/bin/rocblas_smoke.yaml
Traceback (most recent call last):
  File "C:\runner\_work\TheRock\TheRock\build\bin\rocblas_gentest.py", line 31, in <module>
    from yaml import CLoader as Loader
ModuleNotFoundError: No module named 'yaml'
```

## Technical Details

See the linked issue. I suspect that these runners don't have PyYAML
installed in the system Python which is being used to open (execute) the
gentest.py files. On my dev machine I have VSCode set to open Python
files which results in a different failure mode. I'm hoping that by
explicitly calling `python *_gentest.py`, the active Python interpreter
in the current virtual environment will be used instead, which should
already have PyYAML installed.

## Test Plan

* Tested extensively on my dev machine
    ```
.\build\dist\rocm\bin\rocblas-test --yaml
./build/dist/rocm/bin/rocblas_smoke.yaml
.\build\dist\rocm\bin\hipblaslt-test --yaml
D:\projects\TheRock\rocm-libraries\projects\hipblaslt\clients\tests\data\smoke_gtest.yaml
.\build\dist\rocm\bin\hipblas-test --yaml
./build/dist/rocm/bin/hipblas_smoke.yaml
    ```
* Opted in to gfx115X-windows tests to see if CI runners are happy with
the change too

## Test Result

* Local tests succeeded
* CI rocblas tests succeeded:
https://github.com/ROCm/TheRock/actions/runs/17445368488/job/49543726892?pr=1383,
see logs `python
C:\runner\_work\TheRock\TheRock\build\bin\/rocblas_gentest.py --template
C:\runner\_work\TheRock\TheRock\build\bin\/rocblas_template.yaml -o
C:\WINDOWS\SystemTemp\rocblas-fu7qHn ./build/bin/rocblas_smoke.yaml`
* CI hipblaslt tests failed but I believe that is unrelated:
https://github.com/ROCm/TheRock/actions/runs/17445368488/job/49543726890?pr=1383#step:5:9668
see `Error allocating (0 GB) host memory`

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.